### ISSUE TITLE
kursvy knapp

### ISSUE THREAD

**Issue by davidsvson** [ZoCom-utbildning/awesomo#13]
på sidan med alla kurser finns det för varje kurs knappar för planering översikt och bedömning. Men att gå till kursvyn är ingen egen knapp utan bara att trycka någon stans där det inte finns en knapp. 
Skulle kännas mer enhetligt om kursvy också hadde en knapp

**Comment by zocom-johan-kivi** [comment]
Nu finns det en knapp där. Jag passade även på att redesigna knapparna lite så nu är de inte lika "in your face".
