### ISSUE TITLE
Fel klockslag på inskickad inlämning

### ISSUE THREAD

**Issue by antonekstrom1** [ZoCom-utbildning/awesomo#16]
När man skickat in sin inlämning anges felaktigt klockslag se skärmdump: https://gyazo.com/4d19224a3a39cdfe8cbef05e0667d4b0

**Comment by zocom-johan-kivi** [comment]
Borde bara löst nu! Var en missmatch mellan server timezon och klient. Kika om det ser rätt ut nu?

**Comment by antonekstrom1** [comment]
Kanonbra Johan! Det ser fortfarande likadant ut dvs samma tid kl 13:11. Förmodligen så behöver jag lämna in den på nytt igen för att kunna se ifall det är rätt klockslag. Återkommer vid nästa inlämning ifall det kvarstår.

**Comment by Feistybeard** [comment]
Kan nämna att jag lämnade in idag och fick även jag fel klockslag på inlämningen. Fick Kl17:11 när jag borde fått Kl19:11 så det måste fortfarande vara nått fel gällande tidszon.

**Comment by zocom-johan-kivi** [comment]
Ok, har hittat buggen. Fick tydligen tillbaka timestamp 2h off på just inlämningar! 
Fixat och pushat!
