### ISSUE TITLE
tidslinje kopplad till moduler

### ISSUE THREAD

**Issue by davidsvson** [ZoCom-utbildning/awesomo#17]
**Is your feature request related to a problem? Please describe.**
Svårt att se kopplingen mellan tidslinjen och modulinformationen som finns listad där under.

Kanske man skulle skriva ut modulens siffra även i tidslinjen och att man kan trycka i tidslinjen för att hoppa till rätt modul

<img width="962" alt="Skärmavbild 2022-09-03 kl  12 29 43" src="https://user-images.githubusercontent.com/6167993/188266578-14c8ab51-35f5-4a80-b4c2-392fd92b7f5a.png">

**Comment by zocom-johan-kivi** [comment]
Siffror inlagda framför modultiteln.
