### ISSUE TITLE
tid på schemalagda möten visar ej minuter

### ISSUE THREAD

**Issue by davidsvson** [ZoCom-utbildning/awesomo#19]
**Describe the bug**

Schemalagd tid visar inte minuter korrekt

har schemalagt ett möte mellan 9.00-9.15 men det visar 9.00-9.00 i kursvyn

<img width="483" alt="Skärmavbild 2022-09-07 kl  12 08 26" src="https://user-images.githubusercontent.com/6167993/188852472-0b09200f-a809-4963-8030-ffd4d96dbaa3.png">

**Comment by zocom-johan-kivi** [comment]
användarfel.
