### ISSUE TITLE
Procent genomförd kurs

### ISSUE THREAD

**Issue by akickia** [ZoCom-utbildning/awesomo#22]
**Describe the bug**
När jag ser på mina studieresultat så står två olika procent, se bild. 
Jag tänkte först att det var en sammanslagning av alla kurser som visades högst upp, men inte heller detta stämmer. 

**To Reproduce**
1. Go to '...' Mina studieresultat
2. Click on '....' Kursen UX / UI Grunder

**Expected behavior**
Jag förväntade mig rätt procent. Har svårt att förstå hur procenten räknas ut generellt, är det utifrån hur långt jag kommit i kursen just nu eller hela kursen? Varför är procenten på första kursen "introduktion till It-branchen och frontendutvecklare" inte 100 trots att alla moment är genomförda? Lite förtydligande kanske vore bra för att bättre ha nytta av den. 

**Screenshots**
![Skärmbild 2022-09-13 095539](https://user-images.githubusercontent.com/95421577/189845925-123fe757-f039-4113-b70e-5d5747612707.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 105.0.5195.102

**Additional context**
Inte ett stort problem för att använda lmz, men tillräckligt för att störa min användarupplevelse något ;)

**Comment by zocom-johan-kivi** [comment]
Tack för feedback!
Vi ska kalibrera procenten lite. 
% genomför kurs ( + utbildning ) baseras på antal gjorda aktiviteter av de som finns utlagda i planeringen.

För tillfället räknas inte examinationerna med i aktiviteterna då vi inte riktigt vet hur vi ska göra där likt du påpekade på ledningsgruppsmötet. Det gör att den totala summan inte blir 100%.

Det ligger ett förslag ute nu på livetillfällen + examinationer som du gärna får kika in! Där man självskattar hur lärorikt man tyckte examinationen var.

**Comment by akickia** [comment]
Hej!
Tack för feedback!
Jag tycker det ser mycket bättre ut på livetillfällena/examinationerna nu
och gillar också att man kan fälla ihop avslutade moduler. Suveränt 👍
Störde mig lite på att min introduktionskurs inte stod på 100% genomförd,
men insåg att det var för att jag inte klickat på alla länkar t.ex. till
vscode och liveserver-extension (eftersom jag redan hade dem installerade).
Gick tillbaka och klickade och nu är det 100%. 😀 Frågan är om det krävs
att man t.ex. klickar på alla presentationer och inspelningar som läggs upp
också för att det ska bli 100% i slutändan, eller går det att exkludera
dem?

Tack och trevlig helg!

Mvh Kicki Lindstrand


Den fre 16 sep. 2022 16:04Johan Kivi ***@***.***> skrev:

**Comment by zocom-johan-kivi** [comment]
Va bra att det ordnade sig! 

Klick på resurser ( länkar till videos, repon etc ) är inget som räknas med utan det är endast självbedömningen som räknas in.

**Comment by akickia** [comment]
Hmm, så konstigt för jag ändrade inget i självskattningen, klickade bara på
alla länkar och då blev avklarade aktiviteter 100%. Men då vet jag att det
är så det ska fungera :)

Den fre 16 sep. 2022 16:43Johan Kivi ***@***.***> skrev:

**Comment by zocom-johan-kivi** [comment]
hmm, konstigt. Jag har kvar denna issue och undersöker saken lite närmare. Låter som ett konstigt beteende.

**Comment by zocom-johan-kivi** [comment]
Har undersökt detta och hittar inget fel. Lyckas inte heller reproducera buggen, så kanske det var en cache-grej i webbläsaren? Jag stänger denna ihop om att det inte är något systemfel någonstans.
