### ISSUE TITLE
Close parts of the course

### ISSUE THREAD

**Issue by claratoll** [ZoCom-utbildning/awesomo#23]
Hi! I think it would be nice to be able to close the parts of the course that we already covered, so it would be easier to navigate. Now you can navigate in the top menu but it would still be nice to close the parts we've done.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zocom-johan-kivi** [comment]
Bra idé Clara! Jag kikar hur det kan se ut och skriver uppdatering här!

**Comment by zocom-johan-kivi** [comment]
Nu har jag implementerat 1.0 av denna. Du har en liten toggle högst upp under kursöversikten som "kompaktar ihop" alla självbedömda moduler och aktiviteter. Dock kan du inte fälla ihop / ut enstaka än, då det kräver en mycket större refaktorering. 

 
<img width="465" alt="Skärmavbild 2022-09-16 kl  14 58 41" src="https://user-images.githubusercontent.com/54580991/190644672-afc38584-75a2-4e33-939c-3a56bd3ec164.png">
