### ISSUE TITLE
Komma in på ny kurs

### ISSUE THREAD

**Issue by nilsson46** [ZoCom-utbildning/awesomo#24]
Fick en undefined sida när jag skulle gå in på nya kursen. Berodde på att jag inte accepterade kursen. Knappen syntes inte så tydligt. Skulle underlätta om det var någon färg på den eller liknande :D 

Antog att jag skulle kunna gå in på den direkt pga inte såg knappen. 

Chrome

**Comment by zocom-johan-kivi** [comment]
Tackar, ska kika upp detta så det blir smärtsamt tydligt att man går in på en kurs man inte tillhör / tackat JA till.

**Comment by nilsson46** [comment]
Detta var troligtvis för att jag använde dark-mode plug-in i webbläsaren!!

Den tis 20 sep. 2022 14:00Johan Kivi ***@***.***> skrev:

**Comment by zocom-johan-kivi** [comment]
Aha, ok. Det förklarar lite. :D 
Har nu fixat ett tydligt felmeddelande om du går in på en kurs du inte har tillgång till.
