### ISSUE TITLE
Datum för fjärrundervisning syns ej

### ISSUE THREAD

**Issue by davidsvson** [ZoCom-utbildning/awesomo#3]
**Describe the bug**

I kursvyn syns endast vilken tid som fjärrundervisningen skall vara det syns inte vilken dag det är.

**Comment by zocom-johan-kivi** [comment]
fixad!

**Comment by davidsvson** [comment]
Ser felaktigt ut. 
"Ons 31/8" visas som "31 31"

**Comment by zocom-johan-kivi** [comment]
Aha, pushen hade inte hunnit byggs om. NU ska de vara klar. Vad god ladda om sidan och kika.
