### ISSUE TITLE
not checkable checkboxes when clicking on box 

### ISSUE THREAD

**Issue by JuliaGloggPete** [ZoCom-utbildning/awesomo#30]
**Describe the bug**
not checkable checkboxes when clicking on box 

**To Reproduce**
1. Go to 'Inlämna uppgift"
2. Click on ' the boxes nothing will happen - as only the text itself is click sensitive'

**Expected behavior**
should check the box

**Screenshots**
![Skärmavbild 2022-11-16 kl  13 44 19](https://user-images.githubusercontent.com/113100420/202184033-bb0b1d32-9191-490b-9e2c-d669f12788b7.png)

**Desktop (please complete the following information):**
 - iOS
 - Browser Safari
 
**Additional context**
not a priority problem, only some funktion that suggests to work differently then it does

**Comment by zocom-johan-kivi** [comment]
Tackar, jag undersöker vad detta beror på!

**Comment by zocom-johan-kivi** [comment]
Bör nu vara fixat!
