### ISSUE TITLE
För lång text bryter layouten

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [ZoCom-utbildning/awesomo#5]
**Describe the bug**
För lång text bryter layouten. Se bild nedan.

<img width="258" alt="Skärmavbild 2022-08-29 kl  13 59 02" src="https://user-images.githubusercontent.com/54267140/187196237-19e4cbd7-56b7-4714-86e1-f79cb0760a7a.png">

**Comment by zocom-johan-kivi** [comment]
fixed, now overflow shows ellipsis ( to lon... ).
