### ISSUE TITLE
Felaktigt datum - Eventuell bugg

### ISSUE THREAD

**Issue by antonekstrom1** [ZoCom-utbildning/awesomo#7]
Fel datum anges vid eventlänkar se nedan skärmdump fast att rätt datum (31 aug) är valt i datumväljaren (uppgift enligt lärare Christoffer).

Skärmdump: https://gyazo.com/9d7fdf1c78af3d128632afbad9419c3a

**Comment by zocom-johan-kivi** [comment]
Tackar. Det var ett "off by one error" som nu bör vara åtgärdat.
