### ISSUE TITLE
Fel antal dagar visas i examinationsrutan

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [ZoCom-utbildning/awesomo#8]
**Describe the bug**
"Antal studiedagar tills inlämning" visar fel dagar då det blir + 1 som finns i nedan kodsnutt.
```
function daysTilDeadline() {
  const left = differenceInBusinessDays(new Date(props.activity.endTime), Date.now()) + 1;
  return left > 1 ? `${left} studiedagar` : `${left} studiedag`;
}
```

**Comment by zocom-johan-kivi** [comment]
Det var date-fns som räknade från morgondagen av någon anledning. Har nu löst det då att den även inkluderar dagens datum.
